//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notic_board_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klass
    {
        public Klass()
        {
            this.user_enrolled_in_classes2 = new HashSet<user_enrolled_in_classes2>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<user_enrolled_in_classes2> user_enrolled_in_classes2 { get; set; }
    }
}
